/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model
{
    /// <summary>
    /// Header of a Word Document (DOCX)
    /// </summary>
    [DataContract]
    public partial class DocxHeader :  IEquatable<DocxHeader>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocxHeader" /> class.
        /// </summary>
        /// <param name="path">The Path of the location of this object; leave blank for new tables.</param>
        /// <param name="paragraphs">Paragraphs in this header.</param>
        /// <param name="sectionsWithHeader">Sections that the header is applied to.</param>
        public DocxHeader(string path = default(string), List<DocxParagraph> paragraphs = default(List<DocxParagraph>), List<DocxSection> sectionsWithHeader = default(List<DocxSection>))
        {
            this.Path = path;
            this.Paragraphs = paragraphs;
            this.SectionsWithHeader = sectionsWithHeader;
        }
        
        /// <summary>
        /// The Path of the location of this object; leave blank for new tables
        /// </summary>
        /// <value>The Path of the location of this object; leave blank for new tables</value>
        [DataMember(Name="Path", EmitDefaultValue=false)]
        public string Path { get; set; }

        /// <summary>
        /// Paragraphs in this header
        /// </summary>
        /// <value>Paragraphs in this header</value>
        [DataMember(Name="Paragraphs", EmitDefaultValue=false)]
        public List<DocxParagraph> Paragraphs { get; set; }

        /// <summary>
        /// Sections that the header is applied to
        /// </summary>
        /// <value>Sections that the header is applied to</value>
        [DataMember(Name="SectionsWithHeader", EmitDefaultValue=false)]
        public List<DocxSection> SectionsWithHeader { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocxHeader {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Paragraphs: ").Append(Paragraphs).Append("\n");
            sb.Append("  SectionsWithHeader: ").Append(SectionsWithHeader).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocxHeader);
        }

        /// <summary>
        /// Returns true if DocxHeader instances are equal
        /// </summary>
        /// <param name="input">Instance of DocxHeader to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocxHeader input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Path == input.Path ||
                    (this.Path != null &&
                    this.Path.Equals(input.Path))
                ) && 
                (
                    this.Paragraphs == input.Paragraphs ||
                    this.Paragraphs != null &&
                    this.Paragraphs.SequenceEqual(input.Paragraphs)
                ) && 
                (
                    this.SectionsWithHeader == input.SectionsWithHeader ||
                    this.SectionsWithHeader != null &&
                    this.SectionsWithHeader.SequenceEqual(input.SectionsWithHeader)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Path != null)
                    hashCode = hashCode * 59 + this.Path.GetHashCode();
                if (this.Paragraphs != null)
                    hashCode = hashCode * 59 + this.Paragraphs.GetHashCode();
                if (this.SectionsWithHeader != null)
                    hashCode = hashCode * 59 + this.SectionsWithHeader.GetHashCode();
                return hashCode;
            }
        }
    }

}
