/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model
{
    /// <summary>
    /// Result of performing an XQuery operation on an XML document.
    /// </summary>
    [DataContract]
    public partial class XmlQueryWithXQueryResult :  IEquatable<XmlQueryWithXQueryResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XmlQueryWithXQueryResult" /> class.
        /// </summary>
        /// <param name="successful">True if the operation was successful, false otherwise.</param>
        /// <param name="resultingXml">Resulting XML result output.</param>
        /// <param name="errorMessage">If an error occurs, additional details on the error.</param>
        public XmlQueryWithXQueryResult(bool? successful = default(bool?), string resultingXml = default(string), string errorMessage = default(string))
        {
            this.Successful = successful;
            this.ResultingXml = resultingXml;
            this.ErrorMessage = errorMessage;
        }
        
        /// <summary>
        /// True if the operation was successful, false otherwise
        /// </summary>
        /// <value>True if the operation was successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Resulting XML result output
        /// </summary>
        /// <value>Resulting XML result output</value>
        [DataMember(Name="ResultingXml", EmitDefaultValue=false)]
        public string ResultingXml { get; set; }

        /// <summary>
        /// If an error occurs, additional details on the error
        /// </summary>
        /// <value>If an error occurs, additional details on the error</value>
        [DataMember(Name="ErrorMessage", EmitDefaultValue=false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class XmlQueryWithXQueryResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  ResultingXml: ").Append(ResultingXml).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as XmlQueryWithXQueryResult);
        }

        /// <summary>
        /// Returns true if XmlQueryWithXQueryResult instances are equal
        /// </summary>
        /// <param name="input">Instance of XmlQueryWithXQueryResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(XmlQueryWithXQueryResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.ResultingXml == input.ResultingXml ||
                    (this.ResultingXml != null &&
                    this.ResultingXml.Equals(input.ResultingXml))
                ) && 
                (
                    this.ErrorMessage == input.ErrorMessage ||
                    (this.ErrorMessage != null &&
                    this.ErrorMessage.Equals(input.ErrorMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.ResultingXml != null)
                    hashCode = hashCode * 59 + this.ResultingXml.GetHashCode();
                if (this.ErrorMessage != null)
                    hashCode = hashCode * 59 + this.ErrorMessage.GetHashCode();
                return hashCode;
            }
        }
    }

}
