/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing ZipArchiveApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ZipArchiveApiTests
    {
        private ZipArchiveApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ZipArchiveApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZipArchiveApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ZipArchiveApi
            //Assert.IsInstanceOfType(typeof(ZipArchiveApi), instance, "instance is a ZipArchiveApi");
        }

        
        /// <summary>
        /// Test ZipArchiveZipCreate
        /// </summary>
        [Test]
        public void ZipArchiveZipCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ZipArchiveZipCreate();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ZipArchiveZipCreateAdvanced
        /// </summary>
        [Test]
        public void ZipArchiveZipCreateAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateZipArchiveRequest request = null;
            //var response = instance.ZipArchiveZipCreateAdvanced(request);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ZipArchiveZipExtract
        /// </summary>
        [Test]
        public void ZipArchiveZipExtractTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //var response = instance.ZipArchiveZipExtract(inputFile);
            //Assert.IsInstanceOf<ZipExtractResponse> (response, "response is ZipExtractResponse");
        }
        
    }

}
