/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEditPdfApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Encrypt and password-protect a PDF
        /// </summary>
        /// <remarks>
        /// Encrypt a PDF document with a password.  Set an owner password to control owner (editor/creator) permissions, and set a user (reader) password to control the viewer of the PDF.  Set the password fields null to omit the given password.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional)</param>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (optional)</param>
        /// <returns>byte[]</returns>
        byte[] EditPdfEncrypt (System.IO.Stream inputFile, string userPassword = null, string ownerPassword = null);

        /// <summary>
        /// Encrypt and password-protect a PDF
        /// </summary>
        /// <remarks>
        /// Encrypt a PDF document with a password.  Set an owner password to control owner (editor/creator) permissions, and set a user (reader) password to control the viewer of the PDF.  Set the password fields null to omit the given password.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional)</param>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> EditPdfEncryptWithHttpInfo (System.IO.Stream inputFile, string userPassword = null, string ownerPassword = null);
        /// <summary>
        /// Rasterize a PDF to an image-based PDF
        /// </summary>
        /// <remarks>
        /// Rasterize a PDF into an image-based PDF.  The output is a PDF where each page is comprised of a high-resolution image, with all text, figures and other components removed.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <returns>byte[]</returns>
        byte[] EditPdfRasterize (System.IO.Stream inputFile);

        /// <summary>
        /// Rasterize a PDF to an image-based PDF
        /// </summary>
        /// <remarks>
        /// Rasterize a PDF into an image-based PDF.  The output is a PDF where each page is comprised of a high-resolution image, with all text, figures and other components removed.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> EditPdfRasterizeWithHttpInfo (System.IO.Stream inputFile);
        /// <summary>
        /// Encrypt, password-protect and set restricted permissions on a PDF
        /// </summary>
        /// <remarks>
        /// Encrypt a PDF document with a password, and set permissions on the PDF.  Set an owner password to control owner (editor/creator) permissions [required], and set a user (reader) password to control the viewer of the PDF [optional].  Set the reader password to null to omit the password.  Restrict or allow printing, copying content, document assembly, editing (read-only), form filling, modification of annotations, and degraded printing through document Digital Rights Management (DRM).
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional) (optional)</param>
        /// <param name="allowPrinting">Set to false to disable printing through DRM.  Default is true. (optional)</param>
        /// <param name="allowDocumentAssembly">Set to false to disable document assembly through DRM.  Default is true. (optional)</param>
        /// <param name="allowContentExtraction">Set to false to disable copying/extracting content out of the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowFormFilling">Set to false to disable filling out form fields in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowEditing">Set to false to disable editing in the PDF through DRM (making the PDF read-only).  Default is true. (optional)</param>
        /// <param name="allowAnnotations">Set to false to disable annotations and editing of annotations in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowDegradedPrinting">Set to false to disable degraded printing of the PDF through DRM.  Default is true. (optional)</param>
        /// <returns>byte[]</returns>
        byte[] EditPdfSetPermissions (string ownerPassword, System.IO.Stream inputFile, string userPassword = null, bool? allowPrinting = null, bool? allowDocumentAssembly = null, bool? allowContentExtraction = null, bool? allowFormFilling = null, bool? allowEditing = null, bool? allowAnnotations = null, bool? allowDegradedPrinting = null);

        /// <summary>
        /// Encrypt, password-protect and set restricted permissions on a PDF
        /// </summary>
        /// <remarks>
        /// Encrypt a PDF document with a password, and set permissions on the PDF.  Set an owner password to control owner (editor/creator) permissions [required], and set a user (reader) password to control the viewer of the PDF [optional].  Set the reader password to null to omit the password.  Restrict or allow printing, copying content, document assembly, editing (read-only), form filling, modification of annotations, and degraded printing through document Digital Rights Management (DRM).
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional) (optional)</param>
        /// <param name="allowPrinting">Set to false to disable printing through DRM.  Default is true. (optional)</param>
        /// <param name="allowDocumentAssembly">Set to false to disable document assembly through DRM.  Default is true. (optional)</param>
        /// <param name="allowContentExtraction">Set to false to disable copying/extracting content out of the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowFormFilling">Set to false to disable filling out form fields in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowEditing">Set to false to disable editing in the PDF through DRM (making the PDF read-only).  Default is true. (optional)</param>
        /// <param name="allowAnnotations">Set to false to disable annotations and editing of annotations in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowDegradedPrinting">Set to false to disable degraded printing of the PDF through DRM.  Default is true. (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> EditPdfSetPermissionsWithHttpInfo (string ownerPassword, System.IO.Stream inputFile, string userPassword = null, bool? allowPrinting = null, bool? allowDocumentAssembly = null, bool? allowContentExtraction = null, bool? allowFormFilling = null, bool? allowEditing = null, bool? allowAnnotations = null, bool? allowDegradedPrinting = null);
        /// <summary>
        /// Add a text watermark to a PDF
        /// </summary>
        /// <remarks>
        /// Adds a text watermark to a PDF
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="watermarkText">Watermark text to add to the PDF (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="fontName">Font Family Name for the watermark text; default is Times New Roman (optional)</param>
        /// <param name="fontSize">Font Size in points of the text; default is 150 (optional)</param>
        /// <param name="fontColor">Font color in hexadecimal or HTML color name; default is Red (optional)</param>
        /// <param name="fontTransparency">Font transparency between 0.0 (completely transparent) to 1.0 (fully opaque); default is 0.5 (optional)</param>
        /// <returns>byte[]</returns>
        byte[] EditPdfWatermarkText (string watermarkText, System.IO.Stream inputFile, string fontName = null, decimal? fontSize = null, string fontColor = null, decimal? fontTransparency = null);

        /// <summary>
        /// Add a text watermark to a PDF
        /// </summary>
        /// <remarks>
        /// Adds a text watermark to a PDF
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="watermarkText">Watermark text to add to the PDF (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="fontName">Font Family Name for the watermark text; default is Times New Roman (optional)</param>
        /// <param name="fontSize">Font Size in points of the text; default is 150 (optional)</param>
        /// <param name="fontColor">Font color in hexadecimal or HTML color name; default is Red (optional)</param>
        /// <param name="fontTransparency">Font transparency between 0.0 (completely transparent) to 1.0 (fully opaque); default is 0.5 (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> EditPdfWatermarkTextWithHttpInfo (string watermarkText, System.IO.Stream inputFile, string fontName = null, decimal? fontSize = null, string fontColor = null, decimal? fontTransparency = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Encrypt and password-protect a PDF
        /// </summary>
        /// <remarks>
        /// Encrypt a PDF document with a password.  Set an owner password to control owner (editor/creator) permissions, and set a user (reader) password to control the viewer of the PDF.  Set the password fields null to omit the given password.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional)</param>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (optional)</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> EditPdfEncryptAsync (System.IO.Stream inputFile, string userPassword = null, string ownerPassword = null);

        /// <summary>
        /// Encrypt and password-protect a PDF
        /// </summary>
        /// <remarks>
        /// Encrypt a PDF document with a password.  Set an owner password to control owner (editor/creator) permissions, and set a user (reader) password to control the viewer of the PDF.  Set the password fields null to omit the given password.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional)</param>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> EditPdfEncryptAsyncWithHttpInfo (System.IO.Stream inputFile, string userPassword = null, string ownerPassword = null);
        /// <summary>
        /// Rasterize a PDF to an image-based PDF
        /// </summary>
        /// <remarks>
        /// Rasterize a PDF into an image-based PDF.  The output is a PDF where each page is comprised of a high-resolution image, with all text, figures and other components removed.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> EditPdfRasterizeAsync (System.IO.Stream inputFile);

        /// <summary>
        /// Rasterize a PDF to an image-based PDF
        /// </summary>
        /// <remarks>
        /// Rasterize a PDF into an image-based PDF.  The output is a PDF where each page is comprised of a high-resolution image, with all text, figures and other components removed.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> EditPdfRasterizeAsyncWithHttpInfo (System.IO.Stream inputFile);
        /// <summary>
        /// Encrypt, password-protect and set restricted permissions on a PDF
        /// </summary>
        /// <remarks>
        /// Encrypt a PDF document with a password, and set permissions on the PDF.  Set an owner password to control owner (editor/creator) permissions [required], and set a user (reader) password to control the viewer of the PDF [optional].  Set the reader password to null to omit the password.  Restrict or allow printing, copying content, document assembly, editing (read-only), form filling, modification of annotations, and degraded printing through document Digital Rights Management (DRM).
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional) (optional)</param>
        /// <param name="allowPrinting">Set to false to disable printing through DRM.  Default is true. (optional)</param>
        /// <param name="allowDocumentAssembly">Set to false to disable document assembly through DRM.  Default is true. (optional)</param>
        /// <param name="allowContentExtraction">Set to false to disable copying/extracting content out of the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowFormFilling">Set to false to disable filling out form fields in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowEditing">Set to false to disable editing in the PDF through DRM (making the PDF read-only).  Default is true. (optional)</param>
        /// <param name="allowAnnotations">Set to false to disable annotations and editing of annotations in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowDegradedPrinting">Set to false to disable degraded printing of the PDF through DRM.  Default is true. (optional)</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> EditPdfSetPermissionsAsync (string ownerPassword, System.IO.Stream inputFile, string userPassword = null, bool? allowPrinting = null, bool? allowDocumentAssembly = null, bool? allowContentExtraction = null, bool? allowFormFilling = null, bool? allowEditing = null, bool? allowAnnotations = null, bool? allowDegradedPrinting = null);

        /// <summary>
        /// Encrypt, password-protect and set restricted permissions on a PDF
        /// </summary>
        /// <remarks>
        /// Encrypt a PDF document with a password, and set permissions on the PDF.  Set an owner password to control owner (editor/creator) permissions [required], and set a user (reader) password to control the viewer of the PDF [optional].  Set the reader password to null to omit the password.  Restrict or allow printing, copying content, document assembly, editing (read-only), form filling, modification of annotations, and degraded printing through document Digital Rights Management (DRM).
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional) (optional)</param>
        /// <param name="allowPrinting">Set to false to disable printing through DRM.  Default is true. (optional)</param>
        /// <param name="allowDocumentAssembly">Set to false to disable document assembly through DRM.  Default is true. (optional)</param>
        /// <param name="allowContentExtraction">Set to false to disable copying/extracting content out of the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowFormFilling">Set to false to disable filling out form fields in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowEditing">Set to false to disable editing in the PDF through DRM (making the PDF read-only).  Default is true. (optional)</param>
        /// <param name="allowAnnotations">Set to false to disable annotations and editing of annotations in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowDegradedPrinting">Set to false to disable degraded printing of the PDF through DRM.  Default is true. (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> EditPdfSetPermissionsAsyncWithHttpInfo (string ownerPassword, System.IO.Stream inputFile, string userPassword = null, bool? allowPrinting = null, bool? allowDocumentAssembly = null, bool? allowContentExtraction = null, bool? allowFormFilling = null, bool? allowEditing = null, bool? allowAnnotations = null, bool? allowDegradedPrinting = null);
        /// <summary>
        /// Add a text watermark to a PDF
        /// </summary>
        /// <remarks>
        /// Adds a text watermark to a PDF
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="watermarkText">Watermark text to add to the PDF (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="fontName">Font Family Name for the watermark text; default is Times New Roman (optional)</param>
        /// <param name="fontSize">Font Size in points of the text; default is 150 (optional)</param>
        /// <param name="fontColor">Font color in hexadecimal or HTML color name; default is Red (optional)</param>
        /// <param name="fontTransparency">Font transparency between 0.0 (completely transparent) to 1.0 (fully opaque); default is 0.5 (optional)</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> EditPdfWatermarkTextAsync (string watermarkText, System.IO.Stream inputFile, string fontName = null, decimal? fontSize = null, string fontColor = null, decimal? fontTransparency = null);

        /// <summary>
        /// Add a text watermark to a PDF
        /// </summary>
        /// <remarks>
        /// Adds a text watermark to a PDF
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="watermarkText">Watermark text to add to the PDF (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="fontName">Font Family Name for the watermark text; default is Times New Roman (optional)</param>
        /// <param name="fontSize">Font Size in points of the text; default is 150 (optional)</param>
        /// <param name="fontColor">Font color in hexadecimal or HTML color name; default is Red (optional)</param>
        /// <param name="fontTransparency">Font transparency between 0.0 (completely transparent) to 1.0 (fully opaque); default is 0.5 (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> EditPdfWatermarkTextAsyncWithHttpInfo (string watermarkText, System.IO.Stream inputFile, string fontName = null, decimal? fontSize = null, string fontColor = null, decimal? fontTransparency = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EditPdfApi : IEditPdfApi
    {
        private Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EditPdfApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EditPdfApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EditPdfApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EditPdfApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Encrypt and password-protect a PDF Encrypt a PDF document with a password.  Set an owner password to control owner (editor/creator) permissions, and set a user (reader) password to control the viewer of the PDF.  Set the password fields null to omit the given password.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional)</param>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (optional)</param>
        /// <returns>byte[]</returns>
        public byte[] EditPdfEncrypt (System.IO.Stream inputFile, string userPassword = null, string ownerPassword = null)
        {
             ApiResponse<byte[]> localVarResponse = EditPdfEncryptWithHttpInfo(inputFile, userPassword, ownerPassword);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Encrypt and password-protect a PDF Encrypt a PDF document with a password.  Set an owner password to control owner (editor/creator) permissions, and set a user (reader) password to control the viewer of the PDF.  Set the password fields null to omit the given password.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional)</param>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > EditPdfEncryptWithHttpInfo (System.IO.Stream inputFile, string userPassword = null, string ownerPassword = null)
        {
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
                throw new ApiException(400, "Missing required parameter 'inputFile' when calling EditPdfApi->EditPdfEncrypt");

            var localVarPath = "/convert/edit/pdf/encrypt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userPassword != null) localVarHeaderParams.Add("userPassword", Configuration.ApiClient.ParameterToString(userPassword)); // header parameter
            if (ownerPassword != null) localVarHeaderParams.Add("ownerPassword", Configuration.ApiClient.ParameterToString(ownerPassword)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("EditPdfEncrypt", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Encrypt and password-protect a PDF Encrypt a PDF document with a password.  Set an owner password to control owner (editor/creator) permissions, and set a user (reader) password to control the viewer of the PDF.  Set the password fields null to omit the given password.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional)</param>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (optional)</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> EditPdfEncryptAsync (System.IO.Stream inputFile, string userPassword = null, string ownerPassword = null)
        {
             ApiResponse<byte[]> localVarResponse = await EditPdfEncryptAsyncWithHttpInfo(inputFile, userPassword, ownerPassword);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Encrypt and password-protect a PDF Encrypt a PDF document with a password.  Set an owner password to control owner (editor/creator) permissions, and set a user (reader) password to control the viewer of the PDF.  Set the password fields null to omit the given password.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional)</param>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> EditPdfEncryptAsyncWithHttpInfo (System.IO.Stream inputFile, string userPassword = null, string ownerPassword = null)
        {
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
                throw new ApiException(400, "Missing required parameter 'inputFile' when calling EditPdfApi->EditPdfEncrypt");

            var localVarPath = "/convert/edit/pdf/encrypt";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userPassword != null) localVarHeaderParams.Add("userPassword", Configuration.ApiClient.ParameterToString(userPassword)); // header parameter
            if (ownerPassword != null) localVarHeaderParams.Add("ownerPassword", Configuration.ApiClient.ParameterToString(ownerPassword)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("EditPdfEncrypt", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Rasterize a PDF to an image-based PDF Rasterize a PDF into an image-based PDF.  The output is a PDF where each page is comprised of a high-resolution image, with all text, figures and other components removed.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <returns>byte[]</returns>
        public byte[] EditPdfRasterize (System.IO.Stream inputFile)
        {
             ApiResponse<byte[]> localVarResponse = EditPdfRasterizeWithHttpInfo(inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Rasterize a PDF to an image-based PDF Rasterize a PDF into an image-based PDF.  The output is a PDF where each page is comprised of a high-resolution image, with all text, figures and other components removed.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > EditPdfRasterizeWithHttpInfo (System.IO.Stream inputFile)
        {
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
                throw new ApiException(400, "Missing required parameter 'inputFile' when calling EditPdfApi->EditPdfRasterize");

            var localVarPath = "/convert/edit/pdf/rasterize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("inputFile", Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("EditPdfRasterize", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Rasterize a PDF to an image-based PDF Rasterize a PDF into an image-based PDF.  The output is a PDF where each page is comprised of a high-resolution image, with all text, figures and other components removed.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> EditPdfRasterizeAsync (System.IO.Stream inputFile)
        {
             ApiResponse<byte[]> localVarResponse = await EditPdfRasterizeAsyncWithHttpInfo(inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Rasterize a PDF to an image-based PDF Rasterize a PDF into an image-based PDF.  The output is a PDF where each page is comprised of a high-resolution image, with all text, figures and other components removed.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> EditPdfRasterizeAsyncWithHttpInfo (System.IO.Stream inputFile)
        {
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
                throw new ApiException(400, "Missing required parameter 'inputFile' when calling EditPdfApi->EditPdfRasterize");

            var localVarPath = "/convert/edit/pdf/rasterize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("inputFile", Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("EditPdfRasterize", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Encrypt, password-protect and set restricted permissions on a PDF Encrypt a PDF document with a password, and set permissions on the PDF.  Set an owner password to control owner (editor/creator) permissions [required], and set a user (reader) password to control the viewer of the PDF [optional].  Set the reader password to null to omit the password.  Restrict or allow printing, copying content, document assembly, editing (read-only), form filling, modification of annotations, and degraded printing through document Digital Rights Management (DRM).
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional) (optional)</param>
        /// <param name="allowPrinting">Set to false to disable printing through DRM.  Default is true. (optional)</param>
        /// <param name="allowDocumentAssembly">Set to false to disable document assembly through DRM.  Default is true. (optional)</param>
        /// <param name="allowContentExtraction">Set to false to disable copying/extracting content out of the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowFormFilling">Set to false to disable filling out form fields in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowEditing">Set to false to disable editing in the PDF through DRM (making the PDF read-only).  Default is true. (optional)</param>
        /// <param name="allowAnnotations">Set to false to disable annotations and editing of annotations in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowDegradedPrinting">Set to false to disable degraded printing of the PDF through DRM.  Default is true. (optional)</param>
        /// <returns>byte[]</returns>
        public byte[] EditPdfSetPermissions (string ownerPassword, System.IO.Stream inputFile, string userPassword = null, bool? allowPrinting = null, bool? allowDocumentAssembly = null, bool? allowContentExtraction = null, bool? allowFormFilling = null, bool? allowEditing = null, bool? allowAnnotations = null, bool? allowDegradedPrinting = null)
        {
             ApiResponse<byte[]> localVarResponse = EditPdfSetPermissionsWithHttpInfo(ownerPassword, inputFile, userPassword, allowPrinting, allowDocumentAssembly, allowContentExtraction, allowFormFilling, allowEditing, allowAnnotations, allowDegradedPrinting);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Encrypt, password-protect and set restricted permissions on a PDF Encrypt a PDF document with a password, and set permissions on the PDF.  Set an owner password to control owner (editor/creator) permissions [required], and set a user (reader) password to control the viewer of the PDF [optional].  Set the reader password to null to omit the password.  Restrict or allow printing, copying content, document assembly, editing (read-only), form filling, modification of annotations, and degraded printing through document Digital Rights Management (DRM).
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional) (optional)</param>
        /// <param name="allowPrinting">Set to false to disable printing through DRM.  Default is true. (optional)</param>
        /// <param name="allowDocumentAssembly">Set to false to disable document assembly through DRM.  Default is true. (optional)</param>
        /// <param name="allowContentExtraction">Set to false to disable copying/extracting content out of the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowFormFilling">Set to false to disable filling out form fields in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowEditing">Set to false to disable editing in the PDF through DRM (making the PDF read-only).  Default is true. (optional)</param>
        /// <param name="allowAnnotations">Set to false to disable annotations and editing of annotations in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowDegradedPrinting">Set to false to disable degraded printing of the PDF through DRM.  Default is true. (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > EditPdfSetPermissionsWithHttpInfo (string ownerPassword, System.IO.Stream inputFile, string userPassword = null, bool? allowPrinting = null, bool? allowDocumentAssembly = null, bool? allowContentExtraction = null, bool? allowFormFilling = null, bool? allowEditing = null, bool? allowAnnotations = null, bool? allowDegradedPrinting = null)
        {
            // verify the required parameter 'ownerPassword' is set
            if (ownerPassword == null)
                throw new ApiException(400, "Missing required parameter 'ownerPassword' when calling EditPdfApi->EditPdfSetPermissions");
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
                throw new ApiException(400, "Missing required parameter 'inputFile' when calling EditPdfApi->EditPdfSetPermissions");

            var localVarPath = "/convert/edit/pdf/encrypt/set-permissions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ownerPassword != null) localVarHeaderParams.Add("ownerPassword", Configuration.ApiClient.ParameterToString(ownerPassword)); // header parameter
            if (userPassword != null) localVarHeaderParams.Add("userPassword", Configuration.ApiClient.ParameterToString(userPassword)); // header parameter
            if (allowPrinting != null) localVarHeaderParams.Add("allowPrinting", Configuration.ApiClient.ParameterToString(allowPrinting)); // header parameter
            if (allowDocumentAssembly != null) localVarHeaderParams.Add("allowDocumentAssembly", Configuration.ApiClient.ParameterToString(allowDocumentAssembly)); // header parameter
            if (allowContentExtraction != null) localVarHeaderParams.Add("allowContentExtraction", Configuration.ApiClient.ParameterToString(allowContentExtraction)); // header parameter
            if (allowFormFilling != null) localVarHeaderParams.Add("allowFormFilling", Configuration.ApiClient.ParameterToString(allowFormFilling)); // header parameter
            if (allowEditing != null) localVarHeaderParams.Add("allowEditing", Configuration.ApiClient.ParameterToString(allowEditing)); // header parameter
            if (allowAnnotations != null) localVarHeaderParams.Add("allowAnnotations", Configuration.ApiClient.ParameterToString(allowAnnotations)); // header parameter
            if (allowDegradedPrinting != null) localVarHeaderParams.Add("allowDegradedPrinting", Configuration.ApiClient.ParameterToString(allowDegradedPrinting)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("EditPdfSetPermissions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Encrypt, password-protect and set restricted permissions on a PDF Encrypt a PDF document with a password, and set permissions on the PDF.  Set an owner password to control owner (editor/creator) permissions [required], and set a user (reader) password to control the viewer of the PDF [optional].  Set the reader password to null to omit the password.  Restrict or allow printing, copying content, document assembly, editing (read-only), form filling, modification of annotations, and degraded printing through document Digital Rights Management (DRM).
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional) (optional)</param>
        /// <param name="allowPrinting">Set to false to disable printing through DRM.  Default is true. (optional)</param>
        /// <param name="allowDocumentAssembly">Set to false to disable document assembly through DRM.  Default is true. (optional)</param>
        /// <param name="allowContentExtraction">Set to false to disable copying/extracting content out of the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowFormFilling">Set to false to disable filling out form fields in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowEditing">Set to false to disable editing in the PDF through DRM (making the PDF read-only).  Default is true. (optional)</param>
        /// <param name="allowAnnotations">Set to false to disable annotations and editing of annotations in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowDegradedPrinting">Set to false to disable degraded printing of the PDF through DRM.  Default is true. (optional)</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> EditPdfSetPermissionsAsync (string ownerPassword, System.IO.Stream inputFile, string userPassword = null, bool? allowPrinting = null, bool? allowDocumentAssembly = null, bool? allowContentExtraction = null, bool? allowFormFilling = null, bool? allowEditing = null, bool? allowAnnotations = null, bool? allowDegradedPrinting = null)
        {
             ApiResponse<byte[]> localVarResponse = await EditPdfSetPermissionsAsyncWithHttpInfo(ownerPassword, inputFile, userPassword, allowPrinting, allowDocumentAssembly, allowContentExtraction, allowFormFilling, allowEditing, allowAnnotations, allowDegradedPrinting);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Encrypt, password-protect and set restricted permissions on a PDF Encrypt a PDF document with a password, and set permissions on the PDF.  Set an owner password to control owner (editor/creator) permissions [required], and set a user (reader) password to control the viewer of the PDF [optional].  Set the reader password to null to omit the password.  Restrict or allow printing, copying content, document assembly, editing (read-only), form filling, modification of annotations, and degraded printing through document Digital Rights Management (DRM).
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ownerPassword">Password of a owner (creator/editor) of the PDF file (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="userPassword">Password of a user (reader) of the PDF file (optional) (optional)</param>
        /// <param name="allowPrinting">Set to false to disable printing through DRM.  Default is true. (optional)</param>
        /// <param name="allowDocumentAssembly">Set to false to disable document assembly through DRM.  Default is true. (optional)</param>
        /// <param name="allowContentExtraction">Set to false to disable copying/extracting content out of the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowFormFilling">Set to false to disable filling out form fields in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowEditing">Set to false to disable editing in the PDF through DRM (making the PDF read-only).  Default is true. (optional)</param>
        /// <param name="allowAnnotations">Set to false to disable annotations and editing of annotations in the PDF through DRM.  Default is true. (optional)</param>
        /// <param name="allowDegradedPrinting">Set to false to disable degraded printing of the PDF through DRM.  Default is true. (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> EditPdfSetPermissionsAsyncWithHttpInfo (string ownerPassword, System.IO.Stream inputFile, string userPassword = null, bool? allowPrinting = null, bool? allowDocumentAssembly = null, bool? allowContentExtraction = null, bool? allowFormFilling = null, bool? allowEditing = null, bool? allowAnnotations = null, bool? allowDegradedPrinting = null)
        {
            // verify the required parameter 'ownerPassword' is set
            if (ownerPassword == null)
                throw new ApiException(400, "Missing required parameter 'ownerPassword' when calling EditPdfApi->EditPdfSetPermissions");
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
                throw new ApiException(400, "Missing required parameter 'inputFile' when calling EditPdfApi->EditPdfSetPermissions");

            var localVarPath = "/convert/edit/pdf/encrypt/set-permissions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ownerPassword != null) localVarHeaderParams.Add("ownerPassword", Configuration.ApiClient.ParameterToString(ownerPassword)); // header parameter
            if (userPassword != null) localVarHeaderParams.Add("userPassword", Configuration.ApiClient.ParameterToString(userPassword)); // header parameter
            if (allowPrinting != null) localVarHeaderParams.Add("allowPrinting", Configuration.ApiClient.ParameterToString(allowPrinting)); // header parameter
            if (allowDocumentAssembly != null) localVarHeaderParams.Add("allowDocumentAssembly", Configuration.ApiClient.ParameterToString(allowDocumentAssembly)); // header parameter
            if (allowContentExtraction != null) localVarHeaderParams.Add("allowContentExtraction", Configuration.ApiClient.ParameterToString(allowContentExtraction)); // header parameter
            if (allowFormFilling != null) localVarHeaderParams.Add("allowFormFilling", Configuration.ApiClient.ParameterToString(allowFormFilling)); // header parameter
            if (allowEditing != null) localVarHeaderParams.Add("allowEditing", Configuration.ApiClient.ParameterToString(allowEditing)); // header parameter
            if (allowAnnotations != null) localVarHeaderParams.Add("allowAnnotations", Configuration.ApiClient.ParameterToString(allowAnnotations)); // header parameter
            if (allowDegradedPrinting != null) localVarHeaderParams.Add("allowDegradedPrinting", Configuration.ApiClient.ParameterToString(allowDegradedPrinting)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("EditPdfSetPermissions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Add a text watermark to a PDF Adds a text watermark to a PDF
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="watermarkText">Watermark text to add to the PDF (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="fontName">Font Family Name for the watermark text; default is Times New Roman (optional)</param>
        /// <param name="fontSize">Font Size in points of the text; default is 150 (optional)</param>
        /// <param name="fontColor">Font color in hexadecimal or HTML color name; default is Red (optional)</param>
        /// <param name="fontTransparency">Font transparency between 0.0 (completely transparent) to 1.0 (fully opaque); default is 0.5 (optional)</param>
        /// <returns>byte[]</returns>
        public byte[] EditPdfWatermarkText (string watermarkText, System.IO.Stream inputFile, string fontName = null, decimal? fontSize = null, string fontColor = null, decimal? fontTransparency = null)
        {
             ApiResponse<byte[]> localVarResponse = EditPdfWatermarkTextWithHttpInfo(watermarkText, inputFile, fontName, fontSize, fontColor, fontTransparency);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Add a text watermark to a PDF Adds a text watermark to a PDF
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="watermarkText">Watermark text to add to the PDF (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="fontName">Font Family Name for the watermark text; default is Times New Roman (optional)</param>
        /// <param name="fontSize">Font Size in points of the text; default is 150 (optional)</param>
        /// <param name="fontColor">Font color in hexadecimal or HTML color name; default is Red (optional)</param>
        /// <param name="fontTransparency">Font transparency between 0.0 (completely transparent) to 1.0 (fully opaque); default is 0.5 (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > EditPdfWatermarkTextWithHttpInfo (string watermarkText, System.IO.Stream inputFile, string fontName = null, decimal? fontSize = null, string fontColor = null, decimal? fontTransparency = null)
        {
            // verify the required parameter 'watermarkText' is set
            if (watermarkText == null)
                throw new ApiException(400, "Missing required parameter 'watermarkText' when calling EditPdfApi->EditPdfWatermarkText");
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
                throw new ApiException(400, "Missing required parameter 'inputFile' when calling EditPdfApi->EditPdfWatermarkText");

            var localVarPath = "/convert/edit/pdf/watermark/text";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (watermarkText != null) localVarHeaderParams.Add("watermarkText", Configuration.ApiClient.ParameterToString(watermarkText)); // header parameter
            if (fontName != null) localVarHeaderParams.Add("fontName", Configuration.ApiClient.ParameterToString(fontName)); // header parameter
            if (fontSize != null) localVarHeaderParams.Add("fontSize", Configuration.ApiClient.ParameterToString(fontSize)); // header parameter
            if (fontColor != null) localVarHeaderParams.Add("fontColor", Configuration.ApiClient.ParameterToString(fontColor)); // header parameter
            if (fontTransparency != null) localVarHeaderParams.Add("fontTransparency", Configuration.ApiClient.ParameterToString(fontTransparency)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("EditPdfWatermarkText", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Add a text watermark to a PDF Adds a text watermark to a PDF
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="watermarkText">Watermark text to add to the PDF (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="fontName">Font Family Name for the watermark text; default is Times New Roman (optional)</param>
        /// <param name="fontSize">Font Size in points of the text; default is 150 (optional)</param>
        /// <param name="fontColor">Font color in hexadecimal or HTML color name; default is Red (optional)</param>
        /// <param name="fontTransparency">Font transparency between 0.0 (completely transparent) to 1.0 (fully opaque); default is 0.5 (optional)</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> EditPdfWatermarkTextAsync (string watermarkText, System.IO.Stream inputFile, string fontName = null, decimal? fontSize = null, string fontColor = null, decimal? fontTransparency = null)
        {
             ApiResponse<byte[]> localVarResponse = await EditPdfWatermarkTextAsyncWithHttpInfo(watermarkText, inputFile, fontName, fontSize, fontColor, fontTransparency);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Add a text watermark to a PDF Adds a text watermark to a PDF
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="watermarkText">Watermark text to add to the PDF (required)</param>
        /// <param name="inputFile">Input file to perform the operation on.</param>
        /// <param name="fontName">Font Family Name for the watermark text; default is Times New Roman (optional)</param>
        /// <param name="fontSize">Font Size in points of the text; default is 150 (optional)</param>
        /// <param name="fontColor">Font color in hexadecimal or HTML color name; default is Red (optional)</param>
        /// <param name="fontTransparency">Font transparency between 0.0 (completely transparent) to 1.0 (fully opaque); default is 0.5 (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> EditPdfWatermarkTextAsyncWithHttpInfo (string watermarkText, System.IO.Stream inputFile, string fontName = null, decimal? fontSize = null, string fontColor = null, decimal? fontTransparency = null)
        {
            // verify the required parameter 'watermarkText' is set
            if (watermarkText == null)
                throw new ApiException(400, "Missing required parameter 'watermarkText' when calling EditPdfApi->EditPdfWatermarkText");
            // verify the required parameter 'inputFile' is set
            if (inputFile == null)
                throw new ApiException(400, "Missing required parameter 'inputFile' when calling EditPdfApi->EditPdfWatermarkText");

            var localVarPath = "/convert/edit/pdf/watermark/text";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (watermarkText != null) localVarHeaderParams.Add("watermarkText", Configuration.ApiClient.ParameterToString(watermarkText)); // header parameter
            if (fontName != null) localVarHeaderParams.Add("fontName", Configuration.ApiClient.ParameterToString(fontName)); // header parameter
            if (fontSize != null) localVarHeaderParams.Add("fontSize", Configuration.ApiClient.ParameterToString(fontSize)); // header parameter
            if (fontColor != null) localVarHeaderParams.Add("fontColor", Configuration.ApiClient.ParameterToString(fontColor)); // header parameter
            if (fontTransparency != null) localVarHeaderParams.Add("fontTransparency", Configuration.ApiClient.ParameterToString(fontTransparency)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("EditPdfWatermarkText", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

    }
}
