/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing AlternateFileFormatCandidate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlternateFileFormatCandidateTests
    {
        // TODO uncomment below to declare an instance variable for AlternateFileFormatCandidate
        //private AlternateFileFormatCandidate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlternateFileFormatCandidate
            //instance = new AlternateFileFormatCandidate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlternateFileFormatCandidate
        /// </summary>
        [Test]
        public void AlternateFileFormatCandidateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlternateFileFormatCandidate
            //Assert.IsInstanceOfType<AlternateFileFormatCandidate> (instance, "variable 'instance' is a AlternateFileFormatCandidate");
        }


        /// <summary>
        /// Test the property 'Probability'
        /// </summary>
        [Test]
        public void ProbabilityTest()
        {
            // TODO unit test for the property 'Probability'
        }
        /// <summary>
        /// Test the property 'DetectedFileExtension'
        /// </summary>
        [Test]
        public void DetectedFileExtensionTest()
        {
            // TODO unit test for the property 'DetectedFileExtension'
        }
        /// <summary>
        /// Test the property 'DetectedMimeType'
        /// </summary>
        [Test]
        public void DetectedMimeTypeTest()
        {
            // TODO unit test for the property 'DetectedMimeType'
        }

    }

}
