/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing AutodetectGetInfoResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AutodetectGetInfoResultTests
    {
        // TODO uncomment below to declare an instance variable for AutodetectGetInfoResult
        //private AutodetectGetInfoResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AutodetectGetInfoResult
            //instance = new AutodetectGetInfoResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AutodetectGetInfoResult
        /// </summary>
        [Test]
        public void AutodetectGetInfoResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AutodetectGetInfoResult
            //Assert.IsInstanceOfType<AutodetectGetInfoResult> (instance, "variable 'instance' is a AutodetectGetInfoResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'DetectedFileExtension'
        /// </summary>
        [Test]
        public void DetectedFileExtensionTest()
        {
            // TODO unit test for the property 'DetectedFileExtension'
        }
        /// <summary>
        /// Test the property 'DetectedMimeType'
        /// </summary>
        [Test]
        public void DetectedMimeTypeTest()
        {
            // TODO unit test for the property 'DetectedMimeType'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Test]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'DateModified'
        /// </summary>
        [Test]
        public void DateModifiedTest()
        {
            // TODO unit test for the property 'DateModified'
        }
        /// <summary>
        /// Test the property 'AlternateFileTypeCandidates'
        /// </summary>
        [Test]
        public void AlternateFileTypeCandidatesTest()
        {
            // TODO unit test for the property 'AlternateFileTypeCandidates'
        }

    }

}
