/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing FindStringSimpleResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FindStringSimpleResponseTests
    {
        // TODO uncomment below to declare an instance variable for FindStringSimpleResponse
        //private FindStringSimpleResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FindStringSimpleResponse
            //instance = new FindStringSimpleResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FindStringSimpleResponse
        /// </summary>
        [Test]
        public void FindStringSimpleResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FindStringSimpleResponse
            //Assert.IsInstanceOfType<FindStringSimpleResponse> (instance, "variable 'instance' is a FindStringSimpleResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'Matches'
        /// </summary>
        [Test]
        public void MatchesTest()
        {
            // TODO unit test for the property 'Matches'
        }
        /// <summary>
        /// Test the property 'MatchCount'
        /// </summary>
        [Test]
        public void MatchCountTest()
        {
            // TODO unit test for the property 'MatchCount'
        }

    }

}
