/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing RemoveWhitespaceFromTextRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RemoveWhitespaceFromTextRequestTests
    {
        // TODO uncomment below to declare an instance variable for RemoveWhitespaceFromTextRequest
        //private RemoveWhitespaceFromTextRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RemoveWhitespaceFromTextRequest
            //instance = new RemoveWhitespaceFromTextRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RemoveWhitespaceFromTextRequest
        /// </summary>
        [Test]
        public void RemoveWhitespaceFromTextRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RemoveWhitespaceFromTextRequest
            //Assert.IsInstanceOfType<RemoveWhitespaceFromTextRequest> (instance, "variable 'instance' is a RemoveWhitespaceFromTextRequest");
        }


        /// <summary>
        /// Test the property 'TextContainingWhitespace'
        /// </summary>
        [Test]
        public void TextContainingWhitespaceTest()
        {
            // TODO unit test for the property 'TextContainingWhitespace'
        }

    }

}
