/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing TextDocumentElement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TextDocumentElementTests
    {
        // TODO uncomment below to declare an instance variable for TextDocumentElement
        //private TextDocumentElement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TextDocumentElement
            //instance = new TextDocumentElement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TextDocumentElement
        /// </summary>
        [Test]
        public void TextDocumentElementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TextDocumentElement
            //Assert.IsInstanceOfType<TextDocumentElement> (instance, "variable 'instance' is a TextDocumentElement");
        }


        /// <summary>
        /// Test the property 'ElementNumber'
        /// </summary>
        [Test]
        public void ElementNumberTest()
        {
            // TODO unit test for the property 'ElementNumber'
        }
        /// <summary>
        /// Test the property 'ElementContents'
        /// </summary>
        [Test]
        public void ElementContentsTest()
        {
            // TODO unit test for the property 'ElementContents'
        }

    }

}
