/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing XlsxSpreadsheetCell
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class XlsxSpreadsheetCellTests
    {
        // TODO uncomment below to declare an instance variable for XlsxSpreadsheetCell
        //private XlsxSpreadsheetCell instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of XlsxSpreadsheetCell
            //instance = new XlsxSpreadsheetCell();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of XlsxSpreadsheetCell
        /// </summary>
        [Test]
        public void XlsxSpreadsheetCellInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" XlsxSpreadsheetCell
            //Assert.IsInstanceOfType<XlsxSpreadsheetCell> (instance, "variable 'instance' is a XlsxSpreadsheetCell");
        }


        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'TextValue'
        /// </summary>
        [Test]
        public void TextValueTest()
        {
            // TODO unit test for the property 'TextValue'
        }
        /// <summary>
        /// Test the property 'CellIdentifier'
        /// </summary>
        [Test]
        public void CellIdentifierTest()
        {
            // TODO unit test for the property 'CellIdentifier'
        }
        /// <summary>
        /// Test the property 'StyleIndex'
        /// </summary>
        [Test]
        public void StyleIndexTest()
        {
            // TODO unit test for the property 'StyleIndex'
        }
        /// <summary>
        /// Test the property 'Formula'
        /// </summary>
        [Test]
        public void FormulaTest()
        {
            // TODO unit test for the property 'Formula'
        }

    }

}
