/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NETCore.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing XmlRemoveAllChildrenWithXPathResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class XmlRemoveAllChildrenWithXPathResultTests
    {
        // TODO uncomment below to declare an instance variable for XmlRemoveAllChildrenWithXPathResult
        //private XmlRemoveAllChildrenWithXPathResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of XmlRemoveAllChildrenWithXPathResult
            //instance = new XmlRemoveAllChildrenWithXPathResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of XmlRemoveAllChildrenWithXPathResult
        /// </summary>
        [Test]
        public void XmlRemoveAllChildrenWithXPathResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" XmlRemoveAllChildrenWithXPathResult
            //Assert.IsInstanceOfType<XmlRemoveAllChildrenWithXPathResult> (instance, "variable 'instance' is a XmlRemoveAllChildrenWithXPathResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'ResultingXmlDocument'
        /// </summary>
        [Test]
        public void ResultingXmlDocumentTest()
        {
            // TODO unit test for the property 'ResultingXmlDocument'
        }
        /// <summary>
        /// Test the property 'NodesEditedCount'
        /// </summary>
        [Test]
        public void NodesEditedCountTest()
        {
            // TODO unit test for the property 'NodesEditedCount'
        }

    }

}
